ubilabs/react-geosuggest

- src/Geosuggest.jsx
These callbacks allow sibling components to see whether the input is focused or not
> Added onFocus and onBlur callbacks to the component

- src/Geosuggest.jsx
Sometimes we want to update the user input from out of the component by
example if we have an application as Uber the direction change dragging
the map, therefore the input needs to change too.
> method to change the value of the user input

- README.md
- example/src/app.js
- src/Geosuggest.jsx
> Expose input changes event

- package.json
Prepublish script added with command to copy css in published module.
> fix: add copy css in build module

- src/Geosuggest.jsx
See #65 - also added a fallback
@madgnome  @ro-ka
> Use labelId instead of address to get the geocode

- src/filter-input-attributes.js
fix the autoComplete case
this is one of the modification (The one i need) needed to solve https://github.com/ubilabs/react-geosuggest/issues/93
> autocomplete -> autoComplete

- .travis.yml
- package.json
- test/Geosuggest_spec.jsx
- test/build.tests.js
- test/fixtures/predictions.js
- test/test_helper.js
I have setup the test infrastructure for the repo. Also added the basic test for  component `Geosuggest`.
Fixes #53
> Test infrastructure

- package.json
* Addresses Unknown Option error when running 'npm run js:example'
> Upgrades babelify

- src/Geosuggest.jsx
- src/input.jsx
Attribute was previously set on the wrong component
> Move autoComplete='off' to src/input.jsx

- README.md
Update the examples in the readme to ES6 syntax
> Update docs to ES6 style

- package.json
- test/Geosuggest_spec.jsx
- test/build.tests.js
- test/fixtures/predictions.js
- test/test_helper.js
This PR adds `src/*.js` to the light-server reload list, and src/*.js to the linter, and test/ to the linter.
It also updates the test cases to pass the linting.
> Update package.json to include all files in linter and light-server reload

- example/src/app.js
- src/Geosuggest.jsx
> feat(on-blur): return current user input

- README.md
Added a note to specify  `geosuggest__suggests--hidden` class is added to auto hide the suggestion list. copy the below style in your CSS file. Resolves #140
> added styling note to the docs. Resolves the issue #140

- README.md
This PR adds the new inline style feature information to the doc.
Referencing the PR to issue #109
> added the inline style feature in the doc

- README.md
This parameter was introduced in #147
> Add documentation for `value` parameter of `onBlur` to readme

- src/Geosuggest.jsx
- src/defaults.js
- src/input.jsx
- test/Geosuggest_spec.jsx
- test/google_stub.js
This PR adds numerous test cases.
It also fixes an issue were some of the test cases already present were not functioning properly (see commit message), and instructs istanbul to ignore some functions which cannot be tested.
> test(Geosuggest): add various test cases and fix some broken tests

- README.md
- example/src/app.js
- src/Geosuggest.jsx
- src/defaults.js
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
Added a callback function when there are no suggestions, to allow developers to handle this case easily, and show some UI indication for example.
> feat(Geosuggest): add onSuggestNoResults callback function

- src/Geosuggest.jsx
- src/input.jsx
- src/suggest-item.jsx
- src/suggest-list.jsx
Add some missing JSDoc comments
> docs: add JSDoc comments

- README.md
Minor updates to the readme:
* update wording of the styling note
* remove a no-break space which was causing a heading to be shifted slightly to the right
> docs(readme): update styling note

- src/Geosuggest.jsx
Fixes server-side rendering for release 1.24.0
> fix(Geosuggest): fix server side rendering

- README.md
Adds note to README explaining the peer dependency change in #200
> docs(README): Update readme with note about peer dependency

- README.md
- src/Geosuggest.jsx
- src/input.jsx
- src/prop-types.js
- test/Geosuggest_spec.jsx
> Add onKeyDown and onKeyPress event handlers to the input field

- src/Geosuggest.jsx
Add BEM class to geosuggest label
> refactor (label): add BEM class to geosuggest label

- README.md
This fixes the issue #218 
Added the list of allowed attributes on input tag to the docs
> Adding the allowed attributes details in the docs

- README.md
Added Google APIs listed to the Readme, fixing #226)
> Added Google APIs listed to the Readme

- README.md
updated readme file with examples of exposed functions for ease of development to other developers.
The proper usage was inferred but not explicitly explained.
> docs(readme): add examples of exposed functions

- src/Geosuggest.jsx
> Do not use setState to save timer instance.

- README.md
- src/Geosuggest.jsx
- src/prop-types.js
- src/suggest-item.jsx
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
Fixes #197. Reuses the work done by @edudavid in https://github.com/ubilabs/react-geosuggest/pull/198
> Allow adding custom classes to the suggest list and suggest item

- .eslintrc
- src/Geosuggest.jsx
- src/input.jsx
- test/Geosuggest_spec.jsx
https://github.com/ubilabs/react-geosuggest/pull/228#discussion_r92420247
> refactor(refs) Using new refs pattern

- README.md
- src/Geosuggest.jsx
- src/defaults.js
- src/prop-types.js
- src/suggest-item.jsx
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
> Added highlight matched text

- package.json
- src/input.jsx
- src/suggest-item.jsx
- src/suggest-list.jsx
Using only the react-shallow-compare part from #300 by @cherniv.
> use react-addons-shallow-compare instead of react/lib/shallowCompare

- package.json
- src/prop-types.js
Remove warning with react@15.5.*
> Use prop-types package

- README.md
- src/Geosuggest.jsx
- src/defaults.js
- src/prop-types.js
- src/suggest-item.jsx
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
> Trout zen feat/render suggest item

- src/Geosuggest.jsx
> fix: check for console before calling console.error

- README.md
- src/Geosuggest.jsx
- src/input.jsx
- test/Geosuggest_spec.jsx
Let me know if I've missed anything! :)
Closes #269.
> feat(onKeyDown) Expose the onKeyDown event from input. Closes #269.

- README.md
- example/src/app.js
Removes the deprecation warning for the example.
> refactor(example): use ES6 class instead of createClass

- README.md
Just a quick edit to README.md
> Documented selectSuggest() in readme

- README.md
> New Zealand typo fix

- src/filter-input-attributes.js
> fix(attributes): allow title

- package-lock.json
- package.json
- test/Geosuggest_spec.jsx
> feat: upgrade to react 16

- README.md
- src/filter-input-attributes.ts
- test/Geosuggest_spec.tsx
This allows the user to add any data attribute to the input field. Idea based on the PR #445 by @NoureldeanSaed.
> feat: allow any data attributes

- README.md
- example/src/app.tsx
> refactor(example): use function component

- README.md
- example/src/index.html
Fixes a bug where an unsecure connection warning appeared in the console for the example app. Updated all the URLs to https.
> fix: use secure URLs

- README.md
Updating the link to they types section for better checking on what is supported.
> docs: update types link to reference

- package.json
Adds *autocomplete* as a keyword as this is the term used by Google. Suggested by @p-hagmann 👍.
> chore: add autocomplete keyword
