ubilabs/react-geosuggest

- package.json
By pointing the package `main` property to the built file, no transpile steps are necessary when pulling this component into a project.
This fixes issue https://github.com/ubilabs/react-geosuggest/issues/4
> Point package main to dist file

- src/Geosuggest.jsx
Instead of reaching up for the global `google.maps` object, this change allows the wrapping component to pass the google maps lib in as the `googleMaps` props.
This is useful if the `google.maps` object is not globally bound, or for mocking in tests.
If no prop is provided, the default is still to use the global `google.maps` object.
> Pass in google maps global via props

- README.md
- gulpfile.js
- package.json
This is a housekeeping PR which adds:
- Correct typo in readme
- Add license field to `package.json` to prevent warning on `npm install`
- DRY gulp tasks by pushing common tasks into a separate named task
- Add npm scripts entries for each of the gulp tasks so they can be called via `npm run x` without gulp globally installed.
> Houskeeping changes

- example/src/app.js
- package.json
- src/Geosuggest.jsx
Added --extension=.jsx to browserify scripts in order to find those files. Babel automatically searches for those, but not browserify.
Fixes #16.
> Fixed node modules not working by removing jsx extensions in require.

- src/Geosuggest.jsx
This changes might already be there in https://github.com/ubilabs/react-geosuggest/pull/29, but since that included many other changes and is not merged.
Changes summary : 
1. googleMaps object moved out of props so that it can be set at client side in componentDidMount
2. Setting googleMaps and related objects in componentDidMount
I have tested this changes by building the changes and it works fine.
> Support for server side rendering

- src/Geosuggest.jsx
By using LatLng(0, 0) as the default location, react-geosuggest was biasing
results to the Gulf of Guinea.
When radius and location are not supplied to Google's AutocompleteService, it
biases results based on the estimated location of the clients IP address.
> Remove defaults for search radius and location.

- README.md
- src/Geosuggest.jsx
There was some discussion on this in [8](https://github.com/ubilabs/react-geosuggest/issues/8), but for certain use cases it's really nice to be able to put a class on the input element. For example, using bootstrap to add a `form-control` class (when not using sass).
> Add property for input class name.

- src/Geosuggest.jsx
Was working without internet and `google && google.maps` was causing an issue with `"use strict;"` (because the google namespace was not declared). Further, if the `googleMaps` var was falsely the component still tried to initialize.
> "use strict"; no longer throws errors if google cannot be loaded

- src/Geosuggest.jsx
- src/GeosuggestItem.jsx
Just implemented the `ignoreBlur` flag as done in [react-autocomplete](https://github.com/rackt/react-autocomplete/blob/master/lib/Autocomplete.js#L246), but added `onMouseOut` to restore the `ignoreBlur` flag.
The only piece this misses is if a user starts a `mousedown` on a suggestion, and releases the mouse outside of geosuggest. I think it'd be appropriate to use a one-time `mouseup` listener on `document.body` and respond based on it's target, but can see how that'd be debatable. Regardless, I think this is a worthwhile patch -- especially if you don't use the css transition when hiding the suggestions. May also be able to remove the 100ms timeout in `hideSuggests`.
Sidenote: I wanted to use this fork in my app, but since `.gitignore` ignores `module` and `.npmignore` ignores `src`, …
> Fix #60 - use ignoreBlur flag to avoid hiding suggests when clicking one

- src/Geosuggest.jsx
Currently, if the user enters values with special characters, such as a "(" or ")", then an "unbalanced regex" exception is thrown and the search box breaks. This change makes sure to escape the user input string before passing it to the `new Regexp` constructor.
> Escape user input for regex to avoid Exception

- src/Geosuggest.jsx
The `updateSuggests` function has an ES6 "default value" for the `suggestsGoogle` parameter, but this *only* works in the case of an `undefined` value (not `null`).
I've encountered a case where the `autocompleteService` actually returns `null` for  `suggestsGoogle`, and thus I get an error:
```
Uncaught TypeError: Cannot read property 'forEach' of null (Geosuggest.js:248)
>  suggestsGoogle.forEach(function (suggest) {
```
This change handles the `null` case to make it less brittle :smile:
> Handle null value for Google suggestions

- src/suggest-list.jsx
In the docs you suggest you can pass a `className` key to fixtures yet you never carried it forward to the suggest object.
> Add className option for fixtures

- package.json
It seems to be able to update for React v15 with no pain. :grinning: 
Fix #119
> chore: update peer and dev dependencies for React v15

- README.md
- src/Geosuggest.jsx
- src/defaults.js
- test/Geosuggest_spec.jsx
I need to hook into the event that takes place when a new suggestion is activated, so I created an `onActivateSuggest` event prop. Tell me what you think.
> feat(Geosuggest): add onActivateSuggest event

- src/Geosuggest.jsx
- src/filter-input-attributes.js
fixes #136
Some browsers display the default auto complete box on top of the suggestion list if a `name` attribute is set on the Geosuggest element.
I can't think of a situation were having autoComplete enabled would be desirable.
Removing the option and setting it to 'off' by default seems reasonable.
> fix(Geosuggest): Set autoComplete='off' and remove autoComplete option

- src/Geosuggest.jsx
- src/suggest-list.jsx
According to the readme, it is possible to pass fixtures without a location.
If this happens, the fixtures will be automatically geocoded using the label.
This was previously not working. Fixtures without a location attribute were added to the list, but the `onSuggestSelect` event never fired for these fixtures.
This happened because the placeId of fixtures was always set to their label. The GeoCoding function noticed that a placeId was present, and attempted to GeoCode the fixture using the placeId. This PR updates the code to only set the placeId to the label if no GeoCoding is required.
> (fix): GeoCode fixtures when no location is provided

- src/Geosuggest.jsx
- src/suggest-list.jsx
As opposed to #145 this leaves the current API unchanged, except for adding an `isFixture` field to suggests returned in `onSuggestSelect`.
> Re-Implement #145

- example/src/app.js
- src/Geosuggest.jsx
- src/defaults.js
- src/input.jsx
- src/prop-types.js
- src/suggest-item.jsx
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
This supports passing an optional `styles` prop to `Geosuggest`.
This would support overriding/adding styles to the various components.
Syntax: 
```
<Geosuggest
style={{
'input': {
'borderColor': '#000'
},
'suggests': {
'borderColor': '#000'
},
'suggestItem': {
'borderColor': '#000'
'borderWidth': 1
}
}}
/>
```
This PR is in reference with the issue #109
> Support for passing of styles in prop

- README.md
- src/geosuggest.css
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
This fixes a small design bug which was visible when removing focus from the search box while the result set was empty.
> fix(Geosuggest): Hide the suggest list when the result set is empty

- README.md
- src/Geosuggest.jsx
- src/defaults.js
- src/input.jsx
- src/prop-types.js
- test/Geosuggest_spec.jsx
The current behavior of Geosuggest is to trigger `onSelect` when the tab key is pressed in the input field. This PR adds an optional `ignoreTab` property to Geosuggest to disable that behavior. The default behavior is the same as before.
> feat(Geosuggest): Option to ignore tab

- README.md
- package.json
- src/Geosuggest.jsx
- src/defaults.js
- src/prop-types.js
- test/Geosuggest_spec.jsx
I'm implementing debounce in a similar manner to Issue #131, with a default delay of 250ms.
> feat(Geosuggest): Add 'queryDelay' parameter with a default of 250ms

- src/Geosuggest.jsx
This PR fixes a bug where the wrong suggestion was selected under the following circumstances:
* Input field was selected
* User entered some text
* A suggestion was selected using the arrow keys
* The input text was changed so that the new suggestion list did not contain the last selected suggestion anymore
* A new suggest was **NOT** selected using the arrow keys after changing the input
* The user pressed `tab` or `enter`
> fix(Geosuggest): Reset activeSuggest when necessary

- .babelrc
- .eslintrc
- package.json
- src/Geosuggest.jsx
- src/input.jsx
- src/suggest-item.jsx
- src/suggest-list.jsx
Using bind or fat arrows inside of JSX is bad for performance in a number of ways, since it creates new functions on every render. (See https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md for more details of the problem)
I've refactored the existing components to no longer using inline bindings, but instead to be bound as class properties, an ES proposal supported by Babel.
This builds on top of PR #134
> refactor(Geosuggest): Refactor out inline binds in JSX, fix IE11 perf

- src/Geosuggest.jsx
- test/Geosuggest_spec.jsx
This PR fixes two bugs which occur when the `autoActivateFirstSuggest` prop is enabled:
* The activeSuggest continuously wanders down the suggest list while typing a location name
* The activeSuggest is not auto selected in some cases, as `activateSuggest('next')` might be called before the state has finished updating
> fix(Geosuggest): fix `autoActivateFirstSuggest` prop

- README.md
currently the documentation refers the types to https://developers.google.com/places/supported_types which is incorrect since react-geosuggest isn't using the API service directly.
the types should actually refer to the ones in the https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest.
tested in my usages
> correct types documentation

- src/Geosuggest.jsx
- src/input.jsx
Fixes a bug where forms could not be submitted even when suggestions were hidden, as described in #184.
> fix(Geosuggest): allow enter key events to propagate if suggestions are hidden

- package.json
Fixes a bug where:
> npm WARN saveError peer invalid: react@^15.3.1, required by react-addons-shallow-compare@15.3.1
happened when running `npm install` and
> npm ERR! peer invalid: react@^15.3.1, required by react-addons-shallow-compare@15.3.1
happened when running `npm shrinkwrap`.
**BREAKING CHANGE:** react-addons-shallow-compare is now a peer dependency,
meaning users must install it separately from react-geosuggest.
The peer dependency for react allows one to use either react 0.14 or
0.15. However, the dependency for react-addons-shallow-compare only
allows 0.15 versions. For anyone using react 0.14 this causes warnings
from npm saying that the peer dependency for react 0.15 (specified by
react-addons-shallow-compare) is missing. This completely breaks
workflows depending on `npm …
> fix(package): Specify addon as peer dependency

- src/Geosuggest.jsx
- src/input.jsx
- test/Geosuggest_spec.jsx
Fixes a bug where suggestlist was not hidden when input blur is triggered. This bug is mentioned in issue #179
> fixes the bug #179, hides the suggest when input blurs

- README.md
Mention that `geosuggest-item--active` is necessary to make keyboard navigation in the suggestion list "work" visually
> README: A CSS required for keyboard navigation

- src/Geosuggest.jsx
- test/Geosuggest_spec.jsx
Fixes a bug mentioned in issue #193 where `onSuggestSelect` was not fired when geocoding was unsuccessfully.
Made changes to fire `onSuggestSelect` on all cases.
> triggering onSuggestSelect on all condition

- CHANGELOG.md
- README.md
- package.json
- src/input.jsx
- src/suggest-item.jsx
- src/suggest-list.jsx
Removed the peer dependency on react-addons-shallow-compare in favour of reacts internal shallowCompare. Suggested here: https://github.com/ubilabs/react-geosuggest/pull/200#issuecomment-254677912
> refactor(shallowCompare) changed to use reacts internal func

- src/geosuggest.css
There is a duplicate declaration of `font-size` in the `geosuggest.css`. I removed the non `rem` declaration.
- [x ] All tests passing
- [ x] Created tests which fail without the change (if possible)
- [ x] Extended the README / documentation, if necessary
- [ x] Commits and PR follow conventions
> refactor(css): removed dupe font size declaration

- README.md
- src/Geosuggest.jsx
- src/prop-types.js
- src/suggest-item.jsx
- src/suggest-list.jsx
- test/Geosuggest_spec.jsx
Allow user to specify their own class names for active suggestion items and the visibility of the suggestion list.
Closes #223
> feat(style) allow custom hidden list class and active item class

- README.md
- src/Geosuggest.jsx
- src/input.jsx
- test/Geosuggest_spec.jsx
Expose `blur()` similar to `focus()`
Closes #242
> feat: add blur()

- README.md
- src/Geosuggest.jsx
- src/defaults.js
- src/prop-types.js
- test/Geosuggest_spec.jsx
Added maxFixtures prop to allow configuration of the number of fixtures being shown. Default is set to 10 which was hardcoded so far.
https://github.com/ubilabs/react-geosuggest/pull/228#discussion_r92420816
> feat(maxFixtures) Added maxFixtures prop

- README.md
Removed a space between title/link brackets in the Google Maps Javascript API link.
> docs(readme): correct a badly formed link

- README.md
- package.json
- src/filter-input-attributes.js
- src/input.jsx
- src/prop-types.js
Give control to the developer to decide if they want to use autocomplete. This is valuable since some forms begin with name/email/username etc, and they may still want the address to autofill if they autocomplete one of these fields. It is still defaulted to `"off"`, so behavior won't change unless desired.
Closes #303
> Autocomplete as a prop instead of hardcoded - closes #303

- src/input.jsx
The existing code was preventing default input behavior of highlighting
content of the input with shift and arrow keys.
> (fix) allow for shift + arrow key behavior in input box

- .eslintrc
- src/suggest-item.jsx
When there is a lot of fixtures and scroll appears, if you use arrow keys to move through the list you can move to the item which is not visible due to scroll. Fixed it by scrolling item to center if item is not visible.
https://github.com/ubilabs/react-geosuggest/pull/228#discussion_r92421044
> fix(suggest-item) Items are not visible due to scroll when navigating using arrow keys

- src/Geosuggest.jsx
Fixes a bug where the input value after selecting a suggest looks like `[Object object]` happened when you are returning a React element inside the suggest label trough the `getSuggestLabel` prop.
I have found a related closed issue here https://github.com/ubilabs/react-geosuggest/issues/204.
This is the basic approach to solve the issue now and to keep the backward compatibility, but we can think something more complex to keep your API values.
> fix(Geosuggest): add description to keep the original value with custom labels

- src/Geosuggest.jsx
Continuing from #321, instead of ponyfilling we could just replace the call with `filter(...)[0]` as it's a sole use of the method. Filter always returns an array so calling `[0]` could return `undefined` if not found, as it does with `Array.prototype.find`.
Signed-off-by: Pete Nykanen pete.a.nykanen@gmail.com
> fix(Geosuggest.jsx): Use filter over find to fix IE11 compatibility

- src/suggest-item.jsx
On the live demo, when I start typing an address I get the following warning:
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of t`
The issue comes from the makeBold function which is expecting a key parameter. However, it's called without: this.makeBold(suggest.label.substring(start, end))
- [-] Created tests which fail without the change (if possible)
- [-] Extended the README / documentation, if necessary
Fixes #326
> fix(suggest-item): add missing key prop when rendering item

- src/Geosuggest.jsx
Fixes a bug where the geocoder was not taking the `location`, `bounds` and `componentRestrictions` options when geocoding the user's input (no suggestion selected).
**Example**
- I want to autosuggest only places in Switzerland
- I want to bias results around Geneva
- => I define the `location` and `componentRestrictions` props.
- When the user writes "Rue du Lac", only streets with this name around Geneva are suggested: fine
- **BUT** if the user types enter without selecting any suggestion, the input gets geocoded without considering the options and google returns a place in the United States....
This pull requests fixes that behaviour.
As per google docs:
https://developers.google.com/maps/documentation/javascript/geocoding
The `GeocoderRequest` object literal contains the following …
> Fix: Consider location, bounds and componentRestrictions when geocoding

- src/suggest-item.jsx
- test/Geosuggest_spec.jsx
Improve label rendering by spliting only where necessary. also fixes broken ligatures.
Closes #335.
> fix(label formatting): Improve label formatting

- example/src/app.js
- src/Geosuggest.jsx
- test/Geosuggest_spec.jsx
This fixes #201 
When a place is selected and then cleared by erasing the input field, it should also clear out the previous selection from the model.
My fix is to call `onSuggestSelect` with `undefined` so the previously selected place is cleared out
Also added the selected place to the example UI for easy verification
> fix(Geosuggest): clear suggestion on empty input

- README.md
- src/suggest-item.jsx
This PR passes the user input to the `renderSuggest` function. My immediate needs was to allow for easier highlighting solution than what Google Maps returns but I assume this could be useful to others for a bunch of different usecases.
> Passes userInput to the renderSuggest function

- README.md
- src/Geosuggest.jsx
- src/defaults.js
- src/input.jsx
- src/prop-types.js
- test/Geosuggest_spec.jsx
Closes #345.
Rename current internal variable named "ignoreEnter" to "doNotSubmitOnEnter".
Add a new prop type named "ignoreEnter" which can accept
boolean value and default value is false.
If set to true then Input component will ignore Enter key.
Add Unit test case for the new prop.
Add new prop in READ.me file.
Fixes a bug where '...' happened when '...'
> feat(ignoreEnter): add new prop to disable enter key.

- test/Geosuggest_spec.tsx
The unit tests were failing to run due to compilation errors that said, `"Object is possibly 'null'"`
> fix unit test compilation errors

- example/src/index.html
- package-lock.json
- package.json
- rollup.browser.config.js
- rollup.example.config.js
- rollup.module.config.js
Including React and ReactDOM as dependencies was causing the latest version to no longer function when used with React 0.14 and 15.0. See #405. This was due to a breaking change in the way React handles the callback for setState (see here: https://stackoverflow.com/a/48375265/1054890)
The fix was to remove React and ReactDOM as direct dependencies and move them to being peer dependencies. This should be fine, as any project using this component should already have React / ReactDOM as a direct dependency.
Because they are now peer dependencies, the example has been updated to use the versions available via the React CDN links.
> fix(compatibility): change react and reactdom to peer dependencies

- src/Geosuggest.tsx
- src/types/fixture.d.ts
- test/Geosuggest_spec.tsx
We at Uberall.com had been running into issues with the original React GeoSuggest plugin, because sometimes fixtures were not having unique `placeIds`.
Since the respective `placeId` was also used as a React `key`, the React diffing algorithm wasn't working properly due to duplicate `keys`. 
Our solution was to have two separate keys for each fixture: 'label' and 'placeId', where the `label` was used for display, and `placeId` for the `key`. This ensures that each fixtures has its unique `key`.
We also made another custom change by adding a fixture.locationId property to the resulting `suggest`. It enables us to reuse properties passed to the fixture.
> Allow to customize/extend fixture properties

- src/Geosuggest.tsx
- test/Geosuggest_spec.tsx
Closes #423
Use the first suggest when `autoActivateFirstSuggest` is true and `selectSuggest` is called.
> feat: use first suggest on selectSuggest when autoActivateFirstSuggest 

- src/Geosuggest.tsx
- src/suggest-item.tsx
- src/suggest-list.tsx
Fixes deprecation warnings from react. 
The ones for `componentWillReceiveProps`:
```
react-dom.development.js:12466 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod …
```
> fix: warnings for componentWillReceiveProps and componentWillMount

- rollup.module.config.js
Fix https://github.com/ubilabs/react-geosuggest/issues/451
Because they are defined as `dependencies` they should not be bundled.
> Stop bundling classnames and lodash.debounce in module

- src/Geosuggest.tsx
Fixes #457
Fixes a bug where the fixtures didn’t update correctly. Will now update the suggests when the fixtures change.
> fix: catch changing fixtures

- README.md
- src/Geosuggest.tsx
- src/filter-input-attributes.ts
- src/input.tsx
- src/types/props.d.ts
- test/Geosuggest_spec.tsx
Fixes #452, a bug where the random ID for the suggest list makes snapshot tests and enhancing server side rendered apps unusable.
The random ID was added to make the suggest list readable for screen readers, see commit https://github.com/ubilabs/react-geosuggest/commit/b6b7f3dce4f78dddec6cd1c0a74f29c43cfcd171.
This uses an ID that can get passed in and otherwise uses a default ID. The ID then is added to the input and the list with a prefix. Closes #450, too.
> fix: use a not random id for the list

- README.md
- src/Geosuggest.tsx
- src/defaults.ts
- src/input.tsx
- src/types/props.d.ts
Closes #441
Add an `inputType` prop allowing users to use an html `search` input instead with a default value of `text`
> feat(Geosuggest): add option for search input type

- src/Geosuggest.tsx
Fixes a bug where the geocoding wasn’t triggered when calling `selectSuggest` while nothing is active.
Couldn’t write tests as the API call is involved. Need some mocking for this…
> fix: geocode in selectSuggest when nothing selected

- src/Geosuggest.tsx
- src/input.tsx
- src/suggest-list.tsx
- test/Geosuggest_spec.tsx
This PR fixes an accessibility with the current solution
- listbox field does not have a proper label
Fixes :
- https://github.com/ubilabs/react-geosuggest/issues/478
> fix(Geosuggest): fix accessibility

- example/src/app.tsx
- example/src/index.html
- package-lock.json
- package.json
- rollup.browser.config.js
- rollup.example.config.js
- rollup.module.config.js
- test/Geosuggest_spec.tsx
Adds support for React v18, migrates example from ReactDOM.render to createRoot based on [React v18 guide](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).
**NOTE**: Tests are passing, however, they are throwing the ReactDOM.render warning since it seems that even the latest react-dom/test-utils is [still using ReactDOM.render under the hood](https://github.com/facebook/react/blob/main/packages/react-dom/src/test-utils/ReactTestUtils.js#L131). It may be best to migrate tests to something like [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) or simply wait for react-dom to catch up as it isn't affecting test results in any way.
**NOTE**: You may notice a suspicious test change regarding a childNode …
> chore: Support React v18

- example/src/app.tsx
- package-lock.json
- package.json
- src/Geosuggest.tsx
- src/input.tsx
- src/suggest-item.tsx
- src/suggest-list.tsx
- src/types/props.ts
This PR ads support for React 19.
This pull request updates the codebase to ensure compatibility with React 19 and improves type safety by explicitly specifying `React.JSX.Element` instead of `JSX.Element`. The most important changes include modifications to the `package.json` file and updates to various component files to reflect the new type definitions.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L18-R19): Updated `peerDependencies` to include React 19 and updated `@types/react` and `@types/react-dom` to version 19.0.2. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L18-R19) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L37-R38)
* …
> chore(React): Update support react 19

- src/suggest-item.tsx
Fixes #515 by adding a `key` to the returned `<li>` from `suggest-item`. 
This puts a `key` field in both the JSX element `SuggestItem` as well the returned `li`. I don't think there's a downside to having more keys, and this resolves the crashes I was seeing and that were reported in the linked issue.
> fix(geosuggest): Add a key for the returned <li> in suggest-item
